apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: podwithsecretenvvar
  name: podwithsecretenvvar
spec:
  containers:
  - image: nginx
    name: podwithsecretenvvar
    env:
    - name: sqlpassword
      valueFrom:
        secretKeyRef: 
          name: testsecretforenvvar
          key: sqlpassword
          optional: false
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
