apiVersion: v1
kind: Service
metadata:
  labels:
    run: podwithconfig
  name: podwithconfig-svc
  namespace: demo
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80  
  selector:
    tier: front
status:
  loadBalancer: {}
