apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile3
  namespace: deploymentns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 10Gi