apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: testrolebinding
  namespace: ingressapp-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: <user_upn>
